on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - develop-*
      - release/**
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow

env:
  GH_TOKEN: ${{ github.token }}

concurrency: 
  group: ci-merge-checks-${{ github.head_ref || github.run_id }}
  # This workflow has the same group id as the merge checks (e2e tests) workflow.
  # The goal is to cancel pending expensive tests when the PR is set to to draft.
  cancel-in-progress: true

name: Pull Request
jobs:
  change-to-draft:
    name: PR - Set status to draft
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          gh pr ready --undo ${{github.event.number}} -R ${{ github.repository }}
