on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
name: Spartacus github actions
jobs:
  e2eTests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.6.0-chrome77
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - name: Build Spartacus
        run: yarn build:core:lib
      - name: Install cypress dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: projects/storefrontapp-e2e-cypress
      - name: Run e2es
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
        run: yarn e2e:cy:start-run-ci:2005
